# Generated by Django 5.0 on 2024-01-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=10)),
                ('age', models.IntegerField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField(max_length=100)),
                ('bookingdate', models.DateField()),
                ('department', models.CharField(choices=[('general', 'General'), ('ent', 'ENT'), ('orthology', 'Orthology')], max_length=100)),
            ],
        ),
    ]
