# Generated by Django 5.0 on 2024-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phonenumber', models.IntegerField()),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='bookingdate',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('ent', 'ENT'), ('orthology', 'Orthology'), ('gynacology', 'Gynacology'), ('dental clinics', 'Dental Clinics'), ('psycology', 'Psycology'), ('pediatric clinics', 'Pediatric Clinics'), ('ophthalmology', 'Ophthalmology'), ('allergy clinics', 'Allergy Clinics'), ('neurology', 'Neurology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
