# Generated by Django 5.0 on 2024-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_blooddonation_departments_enquery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorsname', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('general', 'General'), ('ent', 'ENT'), ('orthology', 'Orthology'), ('gynacology', 'Gynacology'), ('dental clinics', 'Dental Clinics'), ('psycology', 'Psycology'), ('pediatric clinics', 'Pediatric Clinics'), ('ophthalmology', 'Ophthalmology'), ('allergy clinics', 'Allergy Clinics'), ('neurology', 'Neurology')], max_length=100)),
            ],
        ),
    ]
