# Generated by Django 5.0 on 2024-01-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_loginform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Loginform',
        ),
    ]
