# Generated by Django 5.0 on 2024-01-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_doctors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
