# Generated by Django 5.0 on 2024-01-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
