# Generated by Django 5.0 on 2024-01-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_doctors_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='department',
            new_name='op',
        ),
    ]
