# Generated by Django 5.0 on 2024-01-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_rename_department_appointment_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='details',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='medicine',
        ),
    ]
