# Generated by Django 5.0 on 2024-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_admins'),
    ]

    operations = [
    ]
