# Generated by Django 5.0 on 2024-01-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0019_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
