# Generated by Django 5.0 on 2024-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0022_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('waiting', 'Waiting'), ('checking', 'Checking'), ('checked', 'Checked')], max_length=100),
        ),
    ]
